spring:
  kafka:
    bootstrap-servers: localhost:29092

  application:
    security:
      jwt:
        secret:
          access: vJAJGzMCvBxRLrHx6ufd3aPQj1SZhs8x0cROA+WzI9GUIRr2h4FN/yNUsdYTyZH1ijZzY4QlS/wZI2NFKZy4/g==