server:
  port: 9080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/users/**

        - id: chat-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/messages/**

        - id: chat-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/chats/**
  application:
    security:
      jwt:
        secret:
          access: vJAJGzMCvBxRLrHx6ufd3aPQj1SZhs8x0cROA+WzI9GUIRr2h4FN/yNUsdYTyZH1ijZzY4QlS/wZI2NFKZy4/g==
          refresh: CwwKUIjCmDEau9dyEyjEsDjo17at5BRxCOLrbrDufcV8LxfTLn6Bwxf/99QHMuPyYn4FjKIHu84jhmnj8YcBxQ==
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
